version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '3300:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89E